Some support for keeping track of files compiled without optimization. (See [bug 1817]).
Rev: src/modules/dynamic_module_makefile.in:1.74
Rev: src/modules/static_module_makefile.in:1.65

diff --git a/src/modules/dynamic_module_makefile.in b/src/modules/dynamic_module_makefile.in
--- a/src/modules/dynamic_module_makefile.in
+++ b/src/modules/dynamic_module_makefile.in
@@ -1,5 +1,5 @@
 #
-# $Id: dynamic_module_makefile.in,v 1.73 2001/06/21 22:48:00 hubbe Exp $
+# $Id: dynamic_module_makefile.in,v 1.74 2001/07/06 17:35:43 grubba Exp $
 #
 
 
@@ -62,10 +62,12 @@ dummy:	$(DUMMY) linker_options modlist_headers modlist_segment module.so
 # FIXME: Make this a configure option
 .c.o:
 	@echo "Compiling $<" ;\
+	rm -f $@.fail >/dev/null 2>&1; \
 	if $(CC) $(CFLAGS) -c $< -o $@ ; then : ;\
 	else \
 	  echo "WARNING: Compiler failure! Trying without optimization!" >&2;\
-	  echo "echo $(CC) $(NOOPT_CFLAGS) -c $< -o $@" >&2;\
+	  echo "$(CC) $(NOOPT_CFLAGS) -c $< -o $@" >&2;\
+	  echo "$(CC) $(CFLAGS) -c $< -o $@" >$@.fail ;\
 	  NO_ULIMIT=yes $(CC) $(NOOPT_CFLAGS) -c $< -o $@ ;\
 	fi
 
@@ -110,7 +112,7 @@ module.so: $(OBJS)  $(MODULE_ARCHIVES)
 $(OBJS) : $(MODULE_BASE)/dynamic_module_makefile
 
 clean:
-	-rm -f *.o *.obj *.a *.so module.so linker_options modlist_headers modlist_segment module_testsuite $(MODULE_CLEAN_EXTRA)
+	-rm -f *.o *.fail *.obj *.a *.so module.so linker_options modlist_headers modlist_segment module_testsuite $(MODULE_CLEAN_EXTRA)
 	for a in '' $(MODULE_SUBDIRS) ; do if test "x$$a" = "x"; then :; else echo cleaning $$a ; ( cd $$a ; $(MAKE) $(MAKE_FLAGS) clean ) ; fi ; done
 
 
