Changed module build order in preparation for DLLs: First static modules, then pike core, then dynamic modules. That since DLLs require a .lib corresponding to the .exe file to be able to link.
Rev: src/Makefile.in:1.424
Rev: src/modules/Makefile.in:1.56
Rev: src/modules/common_module_makefile.in:1.39
Rev: src/modules/dynamic_module_makefile.in:1.117
Rev: src/modules/static_module_makefile.in:1.100
Rev: src/post_modules/Makefile.in:1.21

diff --git a/src/modules/dynamic_module_makefile.in b/src/modules/dynamic_module_makefile.in
--- a/src/modules/dynamic_module_makefile.in
+++ b/src/modules/dynamic_module_makefile.in
@@ -1,22 +1,45 @@
 #
-# $Id: dynamic_module_makefile.in,v 1.116 2006/06/18 14:23:54 mast Exp $
+# $Id: dynamic_module_makefile.in,v 1.117 2006/06/18 14:52:32 mast Exp $
 #
 
 LIBGCC=@LIBGCC@
 LC_REQ=@LC_REQ@
 
 LINKAGE_CPPFLAGS=
-LINKAGE_CFLAGS=@CCSHARED@
+DYNAMIC_LINKAGE_CFLAGS=@CCSHARED@
+STATIC_LINKAGE_CFLAGS=
+LINKAGE_CFLAGS=$(DYNAMIC_LINKAGE_CFLAGS)
 
 MODULE_PROGRAM=.$(MODULE_WRAPPER_PREFIX)$(MODNAME)
 MODULE_TARGET=$(TMP_MODULE_BASE)/$(MODDIR)$(MODULE_WRAPPER_PREFIX)$(MODNAME).so
 
+# The reason for this is that we can't use targets directly to specify
+# the build type; many module makefiles depend on being able to
+# override the default target.
+all:
+	@case "x$$MODULE_BUILD_TYPE" in \
+	  xstatic) $(MAKE) $(MAKE_FLAGS) static;; \
+	  xdynamic) $(MAKE) $(MAKE_FLAGS) dynamic;; \
+	  x) $(MAKE) $(MAKE_FLAGS) static dynamic;; \
+	  *) \
+	    echo "Invalid MODULE_BUILD_TYPE: $$MODULE_BUILD_TYPE" >&2; \
+	    exit 1;; \
+	esac
 
 @common_module_makefile@
 
+build_type:
+	@echo dynamic > build_type
+
+static: module-preamble
+	@:
+
+dynamic: module-main
+	@:
+
 linker_options: Makefile
 	@if test "x$(LINKER_OPTIONS)" != x ; then \
-	  echo "LINKER_OPTIONS+=$(LINKER_OPTIONS)" ; \
+	  echo "echo $(LINKER_OPTIONS) > linker_options" ; \
 	else : ; fi ; \
 	echo "$(LINKER_OPTIONS)" >linker_options
 
diff --git a/src/modules/static_module_makefile.in b/src/modules/static_module_makefile.in
--- a/src/modules/static_module_makefile.in
+++ b/src/modules/static_module_makefile.in
@@ -1,5 +1,5 @@
 #
-# $Id: static_module_makefile.in,v 1.99 2006/06/18 14:23:54 mast Exp $
+# $Id: static_module_makefile.in,v 1.100 2006/06/18 14:52:32 mast Exp $
 #
 
 
@@ -11,22 +11,46 @@ LINKAGE_CFLAGS=
 MODULE_PROGRAM=$(MODPATH)$(MODULE_WRAPPER_PREFIX)$(MODNAME)
 MODULE_TARGET=module.a
 
+# The reason for this is that we can't use targets directly to specify
+# the build type; many module makefiles depend on being able to
+# override the default target.
+all:
+	@case "x$$MODULE_BUILD_TYPE" in \
+	  xstatic) $(MAKE) $(MAKE_FLAGS) static;; \
+	  xdynamic) ;; \
+	  x) $(MAKE) $(MAKE_FLAGS) static;; \
+	  *) \
+	    echo "Invalid MODULE_BUILD_TYPE: $$MODULE_BUILD_TYPE" >&2; \
+	    exit 1;; \
+	esac
+
 @common_module_makefile@
 
+build_type:
+	@echo static > build_type
+
+static: module-preamble module-main
+	@:
+
+dynamic:
+	@:
+
 linker_options: Makefile $(MODULE_ARCHIVES)
-	echo >linker_options `pwd`/module.a $(MODULE_LDFLAGS)
-	@for a in '' $(MODULE_ARCHIVES) ; do \
+	@linkopts="`pwd`/module.a $(MODULE_LDFLAGS)"; \
+	for a in '' $(MODULE_ARCHIVES) ; do \
 	  if test "x$$a" = "x"; then :; else \
 	    case "$$a" in \
 	      /*) \
-		echo $$a \
+		linkopts="$$linkopts $$a" \
 	      ;; \
 	      *) \
-		echo `pwd`/$$a \
+		linkopts="$$linkopts `pwd`/$$a" \
 	      ;; \
-            esac >>linker_options; \
+	    esac; \
 	  fi; \
-	done
+	done; \
+	echo "echo $$linkopts > linker_options"; \
+	echo $$linkopts > linker_options
 
 modlist_segment: Makefile
 	@echo >modlist_segment " ,{ \"$(MODULE_PROGRAM)\", pike_module_$(UNIQUE_MODNAME)_init, pike_module_$(UNIQUE_MODNAME)_exit } "
