debian stuff
Rev: packaging/debian/control:1.29
Rev: packaging/debian/rules:1.48

diff --git a/packaging/debian/rules b/packaging/debian/rules
--- a/packaging/debian/rules
+++ b/packaging/debian/rules
@@ -6,7 +6,7 @@
 # architecture-dependant package, as well as an architecture-independent
 # package.
 #
-# $Id: rules,v 1.47 2003/12/19 02:44:46 grendel Exp $
+# $Id: rules,v 1.48 2004/04/28 12:55:05 grendel Exp $
 #
 
 # Uncomment this to turn on verbose mode. 
@@ -199,7 +199,7 @@ install: build
 	-rm -f `find $(CURDIR)/debian/$(PIKE)-core/usr/lib/pike/$(VERSION)/ -name ".autodoc" -type f -print`
 	-@for f in `cat $(CURDIR)/debian/toremove.txt | sed -e 's/@PIKE@/$(PIKE)/g;s/@VERSION@/$(VERSION)/g'`; do \
 	    echo Removing $(CURDIR)/debian/$(PIKE)-core/$$f ; \
-	    rm -f $(CURDIR)/debian/$(PIKE)-core/$$f ; \
+	    rm $(CURDIR)/debian/$(PIKE)-core/$$f &> /dev/null || echo "  FAILED"; \
 	done
 
 	# an eye-candy
