committing
Rev: src/configure:1.9
Rev: src/dependencies:1.3
Rev: src/modules/files/configure:1.5
Rev: src/modules/files/dependencies:1.3
Rev: src/modules/math/dependencies:1.3
Rev: src/modules/pipe/Makefile.in:1.4
Rev: src/modules/pipe/Makefile.in.src:1.2
Rev: src/modules/pipe/dependencies:1.4
Rev: src/modules/regexp/configure:1.4
Rev: src/modules/regexp/dependencies:1.3
Rev: src/modules/spider/Makefile.in:1.4
Rev: src/modules/spider/Makefile.in.src:1.2
Rev: src/modules/spider/dependencies:1.4
Rev: src/modules/sprintf/dependencies:1.3

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -769,6 +769,68 @@ else
   SET_MAKE="MAKE=${MAKE-make}"
 fi
 
+# Extract the first word of "uname", so it can be a program name with args.
+set dummy uname; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+if eval "test \"`echo '$''{'ac_cv_path_uname_prog'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$uname_prog" in
+  /*)
+  ac_cv_path_uname_prog="$uname_prog" # Let the user override the test with a path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_uname_prog="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_uname_prog" && ac_cv_path_uname_prog="no"
+  ;;
+esac
+fi
+uname_prog="$ac_cv_path_uname_prog"
+if test -n "$uname_prog"; then
+  echo "$ac_t""$uname_prog" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+
+# We need some special hacks when running slowaris
+echo $ac_n "checking operating system""... $ac_c" 1>&6
+if eval "test \"`echo '$''{'lpc_cv_sys_os'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+if test "$uname_prog" != "no"; then
+  lpc_cv_sys_os="`uname`"
+
+  if test "$lpc_cv_sys_os" = "SunOS"; then
+    case "`uname -r`" in
+      5.*) lpc_cv_sys_os="Solaris";
+    esac
+  fi
+else
+  lpc_cv_sys_os="Not Solaris"
+fi
+
+fi
+
+echo "$ac_t""$lpc_cv_sys_os" 1>&6
+
+if test "$lpc_cv_sys_os" = "Solaris"; then
+  cat >> confdefs.h <<\EOF
+#define SOLARIS 1
+EOF
+
+  LIBS="$LIBS -lthread"
+fi
+
 
 echo $ac_n "checking first yacc define""... $ac_c" 1>&6
 if eval "test \"`echo '$''{'lpc_cv_yacc_first'+set}'`\" = set"; then
@@ -814,7 +876,7 @@ if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 818 "configure"
+#line 880 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
@@ -851,7 +913,7 @@ else
   ac_cv_c_cross=yes
 else
 cat > conftest.$ac_ext <<EOF
-#line 855 "configure"
+#line 917 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
@@ -872,7 +934,7 @@ if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 876 "configure"
+#line 938 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -894,7 +956,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 898 "configure"
+#line 960 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -912,7 +974,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 916 "configure"
+#line 978 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -933,7 +995,7 @@ if test "$cross_compiling" = yes; then
   ac_cv_header_stdc=no
 else
 cat > conftest.$ac_ext <<EOF
-#line 937 "configure"
+#line 999 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
@@ -971,7 +1033,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 975 "configure"
+#line 1037 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1005,7 +1067,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 1009 "configure"
+#line 1071 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1039,7 +1101,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 1043 "configure"
+#line 1105 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1073,7 +1135,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 1077 "configure"
+#line 1139 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1107,7 +1169,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 1111 "configure"
+#line 1173 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1141,7 +1203,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 1145 "configure"
+#line 1207 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1173,7 +1235,7 @@ if eval "test \"`echo '$''{'ac_cv_type_size_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1177 "configure"
+#line 1239 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1204,7 +1266,7 @@ if eval "test \"`echo '$''{'ac_cv_type_pid_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1208 "configure"
+#line 1270 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1235,7 +1297,7 @@ if eval "test \"`echo '$''{'ac_cv_type_uid_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1239 "configure"
+#line 1301 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 EOF
@@ -1267,7 +1329,7 @@ if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1271 "configure"
+#line 1333 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -1304,7 +1366,7 @@ if eval "test \"`echo '$''{'ac_cv_type_time_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1308 "configure"
+#line 1370 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1341,7 +1403,7 @@ else
   ac_cv_func_memcmp=no
 else
 cat > conftest.$ac_ext <<EOF
-#line 1345 "configure"
+#line 1407 "configure"
 #include "confdefs.h"
 
 main()
@@ -1374,16 +1436,42 @@ fi
 LIBOBJS="${OLD_LIBOBJS}"
 
 
-for ac_func in memset memcpy memchr strchr strrchr fchmod getrusage \
- strcspn crypt _crypt getwd getcwd strtod strtok getenv vfprintf bzero bcopy \
- strtol index rindex vsprintf clock times setlocale strcoll getrlimit  setrlimit
+for ac_func in _crypt \
+ bcopy \
+ bzero \
+ clock \
+ crypt \
+ fchmod \
+ getcwd \
+ getenv \
+ getrlimit \
+ getrusage \
+ getwd \
+ index \
+ memchr \
+ memcpy \
+ memset \
+ rindex \
+ setlocale \
+ setrlimit \
+ strcasecmp \
+ strchr \
+ strcspn \
+ strrchr \
+ strtod \
+ strtok \
+ strtol \
+ times \
+ vfprintf \
+ vsprintf \
+
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1387 "configure"
+#line 1475 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -1440,7 +1528,7 @@ else
    for a in string.h unistd.h stdlib.h
    do
      cat > conftest.$ac_ext <<EOF
-#line 1444 "configure"
+#line 1532 "configure"
 #include "confdefs.h"
 #include <$a>
 EOF
@@ -1473,7 +1561,7 @@ else
    for a in memory.h unistd.h stdlib.h
    do
      cat > conftest.$ac_ext <<EOF
-#line 1477 "configure"
+#line 1565 "configure"
 #include "confdefs.h"
 #include <$a>
 EOF
@@ -1506,7 +1594,7 @@ else
    for a in sys/socket.h sys/socketvar.h sys/socketio.h
    do
      cat > conftest.$ac_ext <<EOF
-#line 1510 "configure"
+#line 1598 "configure"
 #include "confdefs.h"
 #include <$a>
 EOF
@@ -1539,7 +1627,7 @@ else
    for a in stdio.h unistd.h
    do
      cat > conftest.$ac_ext <<EOF
-#line 1543 "configure"
+#line 1631 "configure"
 #include "confdefs.h"
 #include <$a>
 EOF
@@ -1572,7 +1660,7 @@ else
    for a in unistd.h stdlib.h
    do
      cat > conftest.$ac_ext <<EOF
-#line 1576 "configure"
+#line 1664 "configure"
 #include "confdefs.h"
 #include <$a>
 EOF
@@ -1605,7 +1693,7 @@ else
    for a in unistd.h
    do
      cat > conftest.$ac_ext <<EOF
-#line 1609 "configure"
+#line 1697 "configure"
 #include "confdefs.h"
 #include <$a>
 EOF
@@ -1634,7 +1722,7 @@ if eval "test \"`echo '$''{'lpc_cv_sys_free_return'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1638 "configure"
+#line 1726 "configure"
 #include "confdefs.h"
 
 #ifdef HAVE_STDLIB_H
@@ -1687,7 +1775,7 @@ if eval "test \"`echo '$''{'lpc_cv_sys_malloc_return'+set}'`\" = set"; then
 else
   
 cat > conftest.$ac_ext <<EOF
-#line 1691 "configure"
+#line 1779 "configure"
 #include "confdefs.h"
 
 #include <sys/types.h>
@@ -1746,7 +1834,7 @@ if eval "test \"`echo '$''{'ac_cv_header_alloca_h'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1750 "configure"
+#line 1838 "configure"
 #include "confdefs.h"
 #include <alloca.h>
 int main() { return 0; }
@@ -1777,7 +1865,7 @@ if eval "test \"`echo '$''{'ac_cv_func_alloca'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1781 "configure"
+#line 1869 "configure"
 #include "confdefs.h"
 
 #ifdef __GNUC__
@@ -1835,7 +1923,7 @@ if eval "test \"`echo '$''{'ac_cv_os_cray'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1839 "configure"
+#line 1927 "configure"
 #include "confdefs.h"
 #if defined(CRAY) && ! defined(CRAY2)
 webecray
@@ -1863,7 +1951,7 @@ if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1867 "configure"
+#line 1955 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -1917,7 +2005,7 @@ else
   ac_cv_c_stack_direction=0
 else
 cat > conftest.$ac_ext <<EOF
-#line 1921 "configure"
+#line 2009 "configure"
 #include "confdefs.h"
 find_stack_direction ()
 {
@@ -1958,7 +2046,7 @@ if eval "test \"`echo '$''{'ac_cv_c_const'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1962 "configure"
+#line 2050 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -2033,7 +2121,7 @@ else
   ac_cv_c_inline=no
 for ac_kw in inline __inline__ __inline; do
   cat > conftest.$ac_ext <<EOF
-#line 2037 "configure"
+#line 2125 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -2064,6 +2152,45 @@ EOF
 esac
 
 
+echo $ac_n "checking for -lPW""... $ac_c" 1>&6
+if eval "test \"`echo '$''{'ac_cv_lib_PW'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lPW  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 2163 "configure"
+#include "confdefs.h"
+
+int main() { return 0; }
+int t() {
+alloca()
+; return 0; }
+EOF
+if eval $ac_link; then
+  rm -rf conftest*
+  eval "ac_cv_lib_PW=yes"
+else
+  rm -rf conftest*
+  eval "ac_cv_lib_PW=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'PW`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_lib=HAVE_LIB`echo PW | tr '[a-z]' '[A-Z]'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_lib 1
+EOF
+
+  LIBS="-lPW $LIBS"
+
+else
+  echo "$ac_t""no" 1>&6
+fi
+
 echo $ac_n "checking for -lm""... $ac_c" 1>&6
 if eval "test \"`echo '$''{'ac_cv_lib_m'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2071,7 +2198,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lm  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2075 "configure"
+#line 2202 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -2110,7 +2237,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lsocket  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2114 "configure"
+#line 2241 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -2151,7 +2278,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lnsl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2155 "configure"
+#line 2282 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -2192,7 +2319,7 @@ if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2196 "configure"
+#line 2323 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -2254,7 +2381,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2258 "configure"
+#line 2385 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -2316,7 +2443,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2320 "configure"
+#line 2447 "configure"
 #include "confdefs.h"
 
 int main()
@@ -2372,7 +2499,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2376 "configure"
+#line 2503 "configure"
 #include "confdefs.h"
 
 #include <string.h>
@@ -2380,7 +2507,7 @@ char *a="foo bar gazonk";
 char *b="foo";
 char *c="bar";
 char *d="gazonk";
-void main()
+int main()
 {
   if(memmem(b,strlen(b),a,strlen(a))!=a ||
      memmem(c,strlen(c),a,strlen(a))!=(a+4) ||
@@ -2413,6 +2540,51 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+echo $ac_n "checking for working strcoll""... $ac_c" 1>&6
+if eval "test \"`echo '$''{'lpc_cv_func_strcoll'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+cat > conftest.$ac_ext <<EOF
+#line 2553 "configure"
+#include "confdefs.h"
+
+#include <string.h>
+int main()
+{
+  if(strcoll("a","b")< 0 &&
+     strcoll("a","a")==0 &&
+     strcoll("b","a")> 0)
+    exit(0);
+  exit(1);
+}
+
+EOF
+eval $ac_link
+if test -s conftest && (./conftest; exit) 2>/dev/null; then
+  lpc_cv_func_strcoll=yes
+else
+  lpc_cv_func_strcoll=no
+fi
+fi
+rm -fr conftest*
+fi
+
+
+if test "$lpc_cv_func_strcoll" = yes; then
+  echo "$ac_t""yes" 1>&6
+  cat >> confdefs.h <<\EOF
+#define HAVE_STRCOLL 1
+EOF
+
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+
 echo $ac_n "checking for working memmove""... $ac_c" 1>&6
 if eval "test \"`echo '$''{'lpc_cv_func_memmove'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2422,16 +2594,16 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2426 "configure"
+#line 2598 "configure"
 #include "confdefs.h"
 
 #include <string.h>
 char buf[100];
-void main()
+int main()
 {
   strcpy(buf,"foo bar gazonk elefantsnabel.");
   if(strcmp(buf,"foo bar gazonk elefantsnabel.")) exit(1);
-  memmove(buf,buf+1,8);
+  memmove(buf,buf+1,7);
   if(strcmp(buf,"oo bar  gazonk elefantsnabel.")) exit(1);
   memmove(buf+1,buf+1,9);
   if(strcmp(buf,"oo bar  gazonk elefantsnabel.")) exit(1);
@@ -2471,10 +2643,10 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2475 "configure"
+#line 2647 "configure"
 #include "confdefs.h"
 
-void main()
+int main()
 {
   char i,*p;
   i=-10;
@@ -2514,10 +2686,10 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2518 "configure"
+#line 2690 "configure"
 #include "confdefs.h"
 
-void main()
+int main()
 {
   char i,*p;
   i=-10;
@@ -2557,7 +2729,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2561 "configure"
+#line 2733 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -2579,7 +2751,7 @@ int main()
 #if !defined(RLIMIT_NOFILE) && defined(RLIMIT_OFILE)
 #define RLIMIT_NOFILE RLIMIT_OFILE
 #endif
-#if defined(HAVE_GETRLIMIT) && defined(RLIMIT_NOFILE)
+#if defined(HAVE_SETRLIMIT) && defined(RLIMIT_NOFILE)
   struct rlimit lim;
 
   if(getrlimit(RLIMIT_NOFILE,&lim))
@@ -2632,7 +2804,7 @@ if eval "test \"`echo '$''{'lpc_cv_func_getrusage_full'+set}'`\" = set"; then
 else
   
 cat > conftest.$ac_ext <<EOF
-#line 2636 "configure"
+#line 2808 "configure"
 #include "confdefs.h"
 
 #include <sys/time.h>
@@ -2699,7 +2871,7 @@ if eval "test \"`echo '$''{'lpc_cv_getrusage_procfs'+set}'`\" = set"; then
 else
   
 cat > conftest.$ac_ext <<EOF
-#line 2703 "configure"
+#line 2875 "configure"
 #include "confdefs.h"
 
 #include <sys/procfs.h>
@@ -2746,7 +2918,7 @@ if eval "test \"`echo '$''{'lpc_cv_volatile'+set}'`\" = set"; then
 else
   
  cat > conftest.$ac_ext <<EOF
-#line 2750 "configure"
+#line 2922 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -2790,7 +2962,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2794 "configure"
+#line 2966 "configure"
 #include "confdefs.h"
 
 #include <stdarg.h>
@@ -2839,7 +3011,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2843 "configure"
+#line 3015 "configure"
 #include "confdefs.h"
 
 #define TESTING
@@ -2855,7 +3027,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2859 "configure"
+#line 3031 "configure"
 #include "confdefs.h"
 
 #define TESTING
@@ -2871,7 +3043,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2875 "configure"
+#line 3047 "configure"
 #include "confdefs.h"
 
 #define TESTING
@@ -2887,7 +3059,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 2891 "configure"
+#line 3063 "configure"
 #include "confdefs.h"
 
 #define TESTING
@@ -2934,7 +3106,7 @@ MODULE_OBJS=
 module_names=
 for a in `(cd $srcdir/modules ; echo *)`
 do
-  if test "$a" != "CVS" -a "$a" != "RCS"; then
+  if test "$a" != "CVS" -a "$a" != "RCS" ; then
       if test -d "$srcdir/modules/$a" ; then
       dirs="$dirs modules/$a"
       MODULE_OBJS="$MODULE_OBJS modules/$a/$a.a"
@@ -3065,6 +3237,7 @@ s%@YACC@%$YACC%g
 s%@CPP@%$CPP%g
 s%@RANLIB@%$RANLIB%g
 s%@SET_MAKE@%$SET_MAKE%g
+s%@uname_prog@%$uname_prog%g
 s%@LIBOBJS@%$LIBOBJS%g
 s%@ALLOCA@%$ALLOCA%g
 s%@subdirs@%$subdirs%g
