Added documentation target.
Rev: src/Makefile.in:1.254

diff --git a/src/Makefile.in b/src/Makefile.in
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -1,5 +1,5 @@
 #
-# $Id: Makefile.in,v 1.253 2001/03/28 10:02:40 hubbe Exp $
+# $Id: Makefile.in,v 1.254 2001/04/21 15:32:39 grubba Exp $
 #
 
 # This line is needed on some machines.
@@ -181,6 +181,16 @@ POBJ = las.o builtin_functions.o peep.o module.o
 all: module_objects hilfe
 	$(MAKE) $(MAKE_FLAGS) $(MAKE_PARALLEL) post_modules
 	$(MAKE) $(MAKE_FLAGS) $(MAKE_PARALLEL) pike
+
+documentation: just-tinstall
+	@if [ -f "$(SRCDIR)/../autodoc/Makefile" ]; then \
+	  PIKE="`pwd`/test-pike"; \
+	  export PIKE; \
+	  (cd $(SRCDIR)/../autodoc && $(MAKE) PIKE="$$PIKE") || exit 1; \
+	else \
+	  echo "Autodoc directory not found."; \
+	  exit 1; \
+	fi
 
 post_modules: pike
 	@( cd post_modules ; rm remake >/dev/null 2>&1 || : ; \
