Support having an absolute path to the script.
Rev: src/precompile.sh.in:1.10

diff --git a/src/precompile.sh.in b/src/precompile.sh.in
--- a/src/precompile.sh.in
+++ b/src/precompile.sh.in
@@ -100,15 +100,25 @@ esac
 # $SCRIPT work with older versions of Pike - Hubbe
 #
 
-if test -f ./$SCRIPT ; then
-  :
-else
-  if ln -s "$TMP_BINDIR/$SCRIPT"  ./$SCRIPT; then :; else
-    # We might be on a filesystem that doesn't support symlinks (eg FAT).
-    echo "Trying copying instead..."
-    cp "$TMP_BINDIR/$SCRIPT" ./$SCRIPT && chmod 755 ./$SCRIPT
-  fi
-fi
+case "$SCRIPT"; in
+  /*)
+    if test -f "$SCRIPT"; then :; else
+      echo Script "$SCRIPT" not found.
+      exit 1
+    fi
+  ;;
+  *)
+    if test -f ./$SCRIPT ; then
+      :
+    else
+      if ln -s "$TMP_BINDIR/$SCRIPT"  ./$SCRIPT; then :; else
+    	# We might be on a filesystem that doesn't support symlinks (eg FAT).
+    	echo "Trying copying instead..."
+    	cp "$TMP_BINDIR/$SCRIPT" ./$SCRIPT && chmod 755 ./$SCRIPT
+      fi
+    fi
+  ;;
+esac
 
 if test -f ./C.pmod ; then
   :
